First commit in new ec2 server and updated some packages

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -128,13 +128,13 @@ jobs:
             done
 
             # Vérification finale
-            # if curl -f http://localhost:3000 >/dev/null; then
-            #   echo "🎉 Deployment successful! App is healthy."
-            #   echo "📊 PM2 Status:"
-            #   pm2 list
-            # else
-            #   echo "❌ Deployment failed! App is not responding."
-            #   echo "📝 PM2 Logs (last 50 lines):"
-            #   pm2 logs benew-app --lines 50
-            #   exit 1
-            # fi
+            if curl -f http://localhost:3000 >/dev/null; then
+              echo "🎉 Deployment successful! App is healthy."
+              echo "📊 PM2 Status:"
+              pm2 list
+            else
+              echo "❌ Deployment failed! App is not responding."
+              echo "📝 PM2 Logs (last 50 lines):"
+              pm2 logs benew-app --lines 50
+              exit 1
+            fi
